name: nu_mobile
description: Northwestern Mobile
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^3.0.0
  intl: ^0.17.0
  thindek_ui: ^1.0.1
  cupertino_icons: ^1.0.3
  community_material_icon: ^5.9.55
  webview_flutter: ^2.0.10
  provider: ^6.0.2
  auto_route: ^3.2.1
  shared_preferences: ^2.0.6
  flutter_screenutil: ^5.0.0+2
  flutter_easyrefresh: ^2.2.1
  introduction_screen: ^2.1.0
  share: ^2.0.4
  flutter_html: ^2.1.0
  flutter_parsed_text: ^2.2.1
  extended_text: ^8.0.2
  flutter_easyloading: ^3.0.0
  advance_pdf_viewer:
    git:
      url: https://github.com/enveraltin/pdf_viewer.git
  webfeed: ^0.7.0
  flutter_launcher_icons: ^0.9.0
  url_launcher: ^6.0.18
  webviewx: ^0.2.1
  flutter_web_browser: ^0.16.0
  flutter_smart_dialog: ^3.1.0
  new_version: ^0.3.0

  firebase_core: ^1.11.0
  firebase_analytics: ^9.0.5
  firebase_messaging: ^11.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  auto_route_generator: ^3.2.1
  flutter_native_splash: ^1.2.1
  build_runner:


flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/images/nplus_e.png"
  image_path_android: "assets/images/nplus_e.png"
  adaptive_icon_foreground: "assets/images/nplus_tp.png"
  adaptive_icon_background: "assets/images/nplus_bg.png"


flutter_native_splash:
  background_image: "assets/images/nplus_bg.png"
  image: "assets/images/nplus_tp.png"


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/PDF/
    - assets/PDF/tech/
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf


