name: nu_mobile
description: Northwestern Mobile
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.2+5

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^3.0.0
  intl: ^0.17.0
  thindek_ui:
    git:
      url: https://github.com/thindek/thindek_ui.git
  cupertino_icons: ^1.0.3
  community_material_icon: ^5.9.55
  webview_flutter: ^2.0.13
  auto_route: ^3.2.1
  shared_preferences: ^2.0.6
  flutter_screenutil: ^5.0.0+2
  flutter_easyrefresh: ^2.2.1
  introduction_screen: ^2.1.0
  share: ^2.0.4
  flutter_html: ^2.1.0
  flutter_parsed_text: ^2.2.1
#  extended_text: ^8.0.2
  flutter_easyloading: ^3.0.0
  advance_pdf_viewer:
    git:
      url: https://github.com/enveraltin/pdf_viewer.git
  webfeed: ^0.7.0
  flutter_launcher_icons: ^0.9.2
  url_launcher: ^6.0.18
  webviewx: ^0.2.1
  flutter_smart_dialog: ^3.1.0
  new_version: ^0.3.0
  get: ^4.6.1
#  flutter_web_auth: ^0.4.0
  flutter_inappwebview: ^5.3.2

  google_fonts: ^2.3.1
  like_button: ^2.0.4



  firebase_core: ^1.14.1
  firebase_auth: ^3.3.14
  firebase_analytics: ^9.1.5
  firebase_messaging: ^11.2.4
  firebase_remote_config: ^2.0.0
  cloud_firestore: ^3.1.12
  firebase_crashlytics: ^2.6.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  auto_route_generator: ^3.2.1
  flutter_native_splash: ^2.1.5
  build_runner:


flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/images/nplus_e.png"
  image_path_android: "assets/images/nu_432_fg.png"
  adaptive_icon_foreground: "assets/images/nu_432_fg.png"
  adaptive_icon_background: "assets/images/nplus_432_bg.png"


flutter_native_splash:
  background_image: "assets/images/nplus_bg.png"
  image: "assets/images/nplus_tp.png"
  android_12:
  fullscreen: true


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/PDF/
    - assets/PDF/tech/
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf


